services:
  halide:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./container_volume/
        target: /volume
        bind:
          propagation: shared
    container_name: Halide


#####################################################################
# To run the docker compose FOR THE FIRST TIME use these commands
#   docker compose up --build
#
# To run the docker compose AFTER THE FIRST TIME use these commands
#   docker compose run --rm halide /bin/bash
#####################################################################

